name: Build and Push Docker Image

on:
  workflow_run:
    workflows: ["Test in Poetry Environment"]  # The name of the workflow as defined in its 'name' field
    types:
      - completed
    branches:
      - Develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}/app-name:${{ github.sha }}
