name: Build and Push Docker Image

on:
  push:
    branches:
      - dev
      - push_to_container_repo # remove after testing
  workflow_run:
    workflows: [Test in Docker]
      # - "Test in Poetry environment"
    types:
      - completed
    branches:
      - dev
      - push_to_container_repo # remove after testing

permissions:
  contents: write  # Allows write access to contents, which might be necessary for certain actions
  packages: write  # Allows write access to GitHub Packages (e.g., pushing Docker images)

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set repository owner to lowercase
      id: set_lowercase
      run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ghcr.io/${{ env.REPO_OWNER }}/hvv_app:latest
          ghcr.io/${{ env.REPO_OWNER }}/hvv_app:${{ github.sha }}
