name: Test in Docker

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Set up Docker-in-Docker
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build -t hvv_docker .

    - name: Run Docker container
      run: |
        docker run -d -p 8000:8000 -v "$(pwd)/logs:/app/logs" --name hvv_container hvv_docker

    - name: Check Docker container status
      run: docker ps -a

    - name: Inspect Docker logs
      run: docker logs hvv_container

    - name: Get Docker container ID
      id: get_docker_id
      run: |
        echo "container_id=$(docker ps -qf 'ancestor=hvv_docker')" >> $GITHUB_ENV

    - name: Get Docker container IP
      id: get_docker_ip
      run: |
        container_ip=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ${{ env.container_id }})
        echo "container_ip=$container_ip" >> $GITHUB_ENV

    - name: Check if service is running
      run: |
        docker exec ${{ env.container_id }} pgrep -a uvicorn && echo "Service is running" || echo "Service not running"

    - name: Test POST with curl
      run: |
        docker exec ${{ env.container_id }} curl -X POST "http://localhost:8000/data" -H "Content-Type: application/json" -d '{\"entity\": \"An Example Entity\", \"year\": 2023, \"nitrogen_oxide\": 10.5, \"sulphur_dioxide\": 5.2, \"carbon_monoxide\": 3.1, \"organic_carbon\": 2.0, \"nmvoc\": 1.5, \"black_carbon\": 0.8, \"ammonia\": 0.6}'